// data.ts
import { Medicine, Category } from './type';

export const categories: Category[] = [
  { id: 'rare', name: 'Rare Diseases', icon: '🧬', count: 245 },
  { id: 'oncology', name: 'Oncology', icon: '🎗️', count: 189 },
  { id: 'orphan', name: 'Orphan Drugs', icon: '💊', count: 156 },
  { id: 'specialty', name: 'Specialty Meds', icon: '⚕️', count: 312 },
  { id: 'imported', name: 'Imported Drugs', icon: '🌍', count: 78 },
  { id: 'compounded', name: 'Compounded', icon: '🧪', count: 134 }
];

export const featuredMedicines: Medicine[] = [
  {
    id: '1',
    name: 'Kalydeco (Ivacaftor)',
    category: 'Rare Diseases',
    price: 245000,
    originalPrice: 280000,
    image: '🧬',
    rating: 4.8,
    reviews: 24,
    availability: 'In Stock',
    description: 'For Cystic Fibrosis (G551D mutation)',
    prescription: true,
    rare: true,
    keywords: ['kalydeco', 'ivacaftor', 'cystic fibrosis', 'rare disease', 'lung', 'genetic'],
    manufacturer: 'Vertex Pharmaceuticals',
    dosage: '150mg',
    prescriptionRequired: true,
    inStock: true,
    stockQuantity: 25,
    featured: true,
    ingredients: ['Ivacaftor'],
    sideEffects: ['Headache', 'Upper respiratory infection'],
    warnings: ['May cause liver damage']
  },
  {
    id: '2',
    name: 'Spinraza (Nusinersen)',
    category: 'Orphan Drugs',
    price: 1550000,
    originalPrice: 1600000,
    image: '💉',
    rating: 4.9,
    reviews: 18,
    availability: 'Limited Stock',
    description: 'For Spinal Muscular Atrophy',
    prescription: true,
    rare: true,
    keywords: ['spinraza', 'nusinersen', 'spinal muscular atrophy', 'sma', 'muscle', 'genetic'],
    manufacturer: 'Biogen',
    dosage: '12mg',
    prescriptionRequired: true,
    inStock: true,
    stockQuantity: 10,
    featured: true,
    ingredients: ['Nusinersen'],
    sideEffects: ['Fever', 'Headache'],
    warnings: ['May cause respiratory issues']
  },
  {
    id: '3',
    name: 'Zolgensma (Onasemnogene)',
    category: 'Gene Therapy',
    price: 0,
    originalPrice: 0,
    image: '🧪',
    rating: 5.0,
    reviews: 12,
    availability: 'Special Order',
    description: 'Gene therapy for SMA',
    prescription: true,
    rare: true,
    keywords: ['zolgensma', 'onasemnogene', 'gene therapy', 'sma', 'genetic', 'therapy'],
    manufacturer: 'Novartis',
    dosage: '1.1×10^14 vg/kg',
    prescriptionRequired: true,
    inStock: false,
    stockQuantity: 0,
    featured: true,
    ingredients: ['Onasemnogene abeparvovec'],
    sideEffects: ['Vomiting', 'Hepatotoxicity'],
    warnings: ['One-time treatment']
  },
  {
    id: '4',
    name: 'Keytruda (Pembrolizumab)',
    category: 'Oncology',
    price: 185000,
    originalPrice: 210000,
    image: '🎗️',
    rating: 4.7,
    reviews: 45,
    availability: 'In Stock',
    description: 'Immunotherapy for various cancers',
    prescription: true,
    rare: false,
    keywords: ['keytruda', 'pembrolizumab', 'cancer', 'immunotherapy', 'oncology', 'tumor'],
    manufacturer: 'Merck',
    dosage: '200mg',
    prescriptionRequired: true,
    inStock: true,
    stockQuantity: 40,
    featured: false,
    ingredients: ['Pembrolizumab'],
    sideEffects: ['Fatigue', 'Rash'],
    warnings: ['May cause immune-related adverse reactions']
  },
  {
    id: '5',
    name: 'Soliris (Eculizumab)',
    category: 'Rare Diseases',
    price: 320000,
    originalPrice: 350000,
    image: '🔬',
    rating: 4.6,
    reviews: 31,
    availability: 'In Stock',
    description: 'For Paroxysmal Nocturnal Hemoglobinuria',
    prescription: true,
    rare: true,
    keywords: ['soliris', 'eculizumab', 'pnh', 'hemoglobinuria', 'blood disorder', 'complement'],
    manufacturer: 'Alexion Pharmaceuticals',
    dosage: '300mg',
    prescriptionRequired: true,
    inStock: true,
    stockQuantity: 15,
    featured: true,
    ingredients: ['Eculizumab'],
    sideEffects: ['Headache', 'Nausea'],
    warnings: ['Risk of meningococcal infection']
  },
  {
    id: '6',
    name: 'Replagal (Agalsidase alfa)',
    category: 'Orphan Drugs',
    price: 195000,
    originalPrice: 215000,
    image: '🧬',
    rating: 4.5,
    reviews: 28,
    availability: 'Limited Stock',
    description: 'For Fabry Disease',
    prescription: true,
    rare: true,
    keywords: ['replagal', 'agalsidase', 'fabry disease', 'enzyme replacement', 'genetic'],
    manufacturer: 'Shire',
    dosage: '0.2mg/kg',
    prescriptionRequired: true,
    inStock: true,
    stockQuantity: 20,
    featured: true,
    ingredients: ['Agalsidase alfa'],
    sideEffects: ['Fever', 'Chills'],
    warnings: ['May cause infusion reactions']
  },
  {
    id: '7',
    name: 'Cerdelga (Eliglustat)',
    category: 'Rare Diseases',
    price: 450000,
    originalPrice: 480000,
    image: '💊',
    rating: 4.7,
    reviews: 22,
    availability: 'In Stock',
    description: 'For Gaucher Disease Type 1',
    prescription: true,
    rare: true,
    keywords: ['cerdelga', 'eliglustat', 'gaucher disease', 'genetic disorder', 'enzyme'],
    manufacturer: 'Sanofi Genzyme',
    dosage: '84mg',
    prescriptionRequired: true,
    inStock: true,
    stockQuantity: 30,
    featured: true,
    ingredients: ['Eliglustat'],
    sideEffects: ['Diarrhea', 'Fatigue'],
    warnings: ['May cause cardiac arrhythmias']
  },
  {
    id: '8',
    name: 'Opdivo (Nivolumab)',
    category: 'Oncology',
    price: 210000,
    originalPrice: 235000,
    image: '🎗️',
    rating: 4.8,
    reviews: 67,
    availability: 'In Stock',
    description: 'Immunotherapy for melanoma, lung cancer',
    prescription: true,
    rare: false,
    keywords: ['opdivo', 'nivolumab', 'cancer', 'melanoma', 'lung cancer', 'immunotherapy'],
    manufacturer: 'Bristol Myers Squibb',
    dosage: '240mg',
    prescriptionRequired: true,
    inStock: true,
    stockQuantity: 35,
    featured: false,
    ingredients: ['Nivolumab'],
    sideEffects: ['Fatigue', 'Rash'],
    warnings: ['May cause immune-related adverse reactions']
  },
  {
    id: '9',
    name: 'Vyndaqel (Tafamidis)',
    category: 'Rare Diseases',
    price: 300000,
    originalPrice: 320000,
    image: '🧬',
    rating: 4.6,
    reviews: 15,
    availability: 'In Stock',
    description: 'For Transthyretin Amyloidosis',
    prescription: true,
    rare: true,
    keywords: ['vyndaqel', 'tafamidis', 'amyloidosis', 'rare disease', 'protein'],
    manufacturer: 'Pfizer',
    dosage: '20mg',
    prescriptionRequired: true,
    inStock: true,
    stockQuantity: 50,
    featured: true,
    ingredients: ['Tafamidis'],
    sideEffects: ['Nausea', 'Diarrhea'],
    warnings: ['May cause liver damage']
  },
  {
    id: '10',
    name: 'Venclexta (Venetoclax)',
    category: 'Oncology',
    price: 175000,
    originalPrice: 190000,
    image: '🎗️',
    rating: 4.7,
    reviews: 20,
    availability: 'Limited Stock',
    description: 'For Chronic Lymphocytic Leukemia',
    prescription: true,
    rare: false,
    keywords: ['venclexta', 'venetoclax', 'leukemia', 'cancer', 'oncology'],
    manufacturer: 'AbbVie',
    dosage: '100mg',
    prescriptionRequired: true,
    inStock: true,
    stockQuantity: 30,
    featured: false,
    ingredients: ['Venetoclax'],
    sideEffects: ['Fatigue', 'Nausea'],
    warnings: ['May cause tumor lysis syndrome']
  }
];
